"""Added password field

Revision ID: 0be497585c95
Revises: a9864c332b9d
Create Date: 2020-02-26 17:47:40.688359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be497585c95'
down_revision = 'a9864c332b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'password_hash')
    # ### end Alembic commands ###
