"""Naming scheme update

Revision ID: a9864c332b9d
Revises: 67827664d648
Create Date: 2020-02-26 13:43:38.648592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9864c332b9d'
down_revision = '67827664d648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'user_account', ['display_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_column('user_account', 'display_name')
    # ### end Alembic commands ###
